create: создал класс айтем и юзер с основными crud операциями
Artem024/java-shareit pull request #1
Opened 2022-10-27 19:37 UTC by Artem024

2022-10-29 19:41 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User oldUser : oldUsers) {
Этот метод используется и в функции patch. Получается, что пользователь не может обновить свою почту.

2022-10-29 19:42 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> -/**
в репозитории есть еще BookingDTO, который не используется.

2022-10-29 19:44 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryImpl.java
> +            if (item.getAvailable() == null) item.setAvailable(oldItem.getAvailable());
Похоже этот if не нужен. Тут всегда false

2022-10-29 19:50 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto {
Подскажи, пожалуйста, для чего это DTO? В контроллер передается User, далее он идет в сервис, репозиторий, из репозитория возвращается тоже User и только на выходе из контроллера идет преобразование в DTO. Для чего это нужно делать?

2022-10-29 19:51 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/storage/UserInMemoryStorage.java
> +//        Collection<UserDto> usersDto = new ArrayList<>();
Этот комментарий не нужен

2022-10-29 19:52 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть всего немного замечаний

2022-10-31 18:12 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User oldUser : oldUsers) {
Перепроверил, сможет. Этот метод лишь сверяет есть ли имя или email в базе.
В случае функции patch метод не позволит задублить имя или email. 
А индификация пользователя, которого нужно изменить, нам приходит с запроса. т.е. id отдельно обрабатывается

2022-11-01 19:13 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо.

2022-11-01 19:57 UTC, merged