refactor: реализовано хранение в бд, возможность добавлять комментари…
Artem024/java-shareit pull request #2
Opened 2022-11-22 12:27 UTC by Artem024

…и и броинрвоание

2022-11-22 19:32 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +//@Builder
Такие комментарии не нужны

2022-11-22 19:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +
Пустые строки тоже не нужны

2022-11-22 19:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/model/User.java
>   * TODO Sprint add-controllers.
Не нужно оставлять TODO в коде

2022-11-22 19:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@Data
Использование аннотации Data не приветствуется

2022-11-22 19:34 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  import ru.practicum.shareit.item.service.ItemService;
TODO в классе не нужны

2022-11-22 19:35 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryImpl.java
>  public class ItemInMemoryImpl implements ItemStorage {
Похоже этот класс нигде не используется

2022-11-22 19:37 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +public class ItemRepositoryImpl implements ItemRepositoryCustom {
Этот класс нигде не используется. Напиши в ответе на комментарий, если он где-то нужен.

2022-11-22 19:39 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
>      public ErrorResponse anybodyUseEmailException(final AnybodyUseEmailException e) {
Можно объединить те методы, которые обрабатывают эксепшены одинаково

2022-11-22 19:47 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return UserMapper.toUserDto(userRepository.save(user));
2022-11-22 23:44:45.400 ERROR 14457 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

Если два раза добавить пользователя, то падает на стороне базы данных.
Если есть желание, то лучше сделать так, чтобы пользователю приходило сообщение, что такой пользователь уже создан
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.UQ_USER_EMAIL_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'email3@email.com' )"; SQL statement:
insert into users (email, user_name) values (?, ?) [23505-214]

2022-11-22 19:51 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.deleteById(id);
В коде написано, что, если не существует пользователя, которого хотят удалить, то должен быть эксепшн и пользователь должен увидеть нормальное сообщение об ошибке "No %s entity with id %s exists!
delete: http://localhost:8080/users/2222
{
	"timestamp": "2022-11-22T19:48:49.994+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users/2222"
}

org.springframework.dao.EmptyResultDataAccessException: No class ru.practicum.shareit.user.model.User entity with id 2222 exists!

2022-11-22 19:52 UTC, EvgenyKoptubenko requested changes
Совсем немного замечаний. Есть код, который не используется нигде. Есть комментарии, которые не нужны. Можно объединить обработку эксепшенов.

2022-11-23 07:25 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryImpl.java
>  public class ItemInMemoryImpl implements ItemStorage {
Этот класс действительно нигде не используется, это реализация для хранения в памяти
лучше убрать его из кода?

2022-11-23 07:26 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +public class ItemRepositoryImpl implements ItemRepositoryCustom {
Этот используется, подсвечивается как не используемый
прописал над ним @Repository

2022-11-23 07:33 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.deleteById(id);
поправил

2022-11-23 07:34 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +//@Builder
Поправил

2022-11-23 07:34 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +
Поправил

2022-11-23 07:34 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/model/User.java
>   * TODO Sprint add-controllers.
Поправил

2022-11-23 07:34 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  import ru.practicum.shareit.item.service.ItemService;
Поправил

2022-11-23 07:56 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
>      public ErrorResponse anybodyUseEmailException(final AnybodyUseEmailException e) {
Спасибо, почитал, поправил)

2022-11-23 08:36 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        return UserMapper.toUserDto(userRepository.save(user));
а всё
через try cath очень хорошо даже поулчается)

2022-11-23 19:18 UTC, EvgenyKoptubenko approved these changes
Работа сделана очень хорошо. все по ТЗ. Спасибо

2022-11-24 11:25 UTC, merged