create: добавлена возможность делать запросы, добавлены тесты
Artem024/java-shareit pull request #3
Opened 2022-11-30 06:17 UTC by Artem024

2022-11-30 18:42 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        System.out.println("PNX");
Нужно использовать логер

2022-11-30 18:56 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public Collection<ItemRequestDto> getRequests(@RequestHeader("X-Sharer-User-Id") long userId) {
Если отправить запрос на создание request
{
	"id": 17,
	"description": "descriptionItem",
	"requestor": 1,
	"created": "2022-11-30T22:53:49.897194",
	"items": null
}
То потом ничего не возвращается

curl --request POST \
  --url http://localhost:8080/requests/ \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"FilmName",
	"description":"descriptionItem",
	"duration": 22,
	"releaseDate": "2012-04-23T18:25:43.511Z",
	"mpa":{
	  "id":"1",
		"name":"2223"
}
}'

curl --request GET \
  --url http://localhost:8080/requests/all \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1'

2022-11-30 18:58 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Замечаний практически нет.

2022-11-30 19:16 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        System.out.println("PNX");
упс) недотёр)
мне переделать всю работу с логером или пока оставим как есть, а на следующем принте добавить логер?

2022-11-30 19:20 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public void deleteUser(Long id) {
добавил блок try...catch

2022-11-30 19:32 UTC, Artem024 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public Collection<ItemRequestDto> getRequests(@RequestHeader("X-Sharer-User-Id") long userId) {
Попробовал отправить такой запрос, вроде всё получилось, можно попросить уточнить в каких условиях не срабатывает?


Этот момент не с filmorate случаем?
curl --request POST
--url http://localhost:8080/requests/
--header 'Content-Type: application/json'
--header 'X-Sharer-User-Id: 1'
--data '{
"name":"FilmName",
"description":"descriptionItem",
"duration": 22,
"releaseDate": "2012-04-23T18:25:43.511Z",
"mpa":{
"id":"1",
"name":"2223"
}
}'

2022-12-01 19:44 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        System.out.println("PNX");
Можно и на следующем. Ок

2022-12-01 19:45 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public Collection<ItemRequestDto> getRequests(@RequestHeader("X-Sharer-User-Id") long userId) {
Значит мои тестовые запросы не совсем корректны. Если у тебя возвращается, то ок

2022-12-01 19:45 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо

2022-12-01 19:46 UTC, Artem024 commented
Спасибо за ревью!)

2022-12-01 19:46 UTC, merged